FLUID {
    type = "fluid",
    name = "water-saline",
    icon = "__pycoalprocessinggraphics__/graphics/icons/water-saline.png",
    icon_size = 64,
    default_temperature = 25,
    gas_temperature = 35,
    heat_capacity = "1KJ",
    base_color = {r = 0.9, g = 0.9, b = 1},
    flow_color = {r = 0.9, g = 0.9, b = 1},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "py-fluids",
}
