local item_sounds = require("__base__.prototypes.item_sounds")

local function add_sound_item(name, move_sound, pick_sound, drop_sound)
    for item_type in pairs(defines.prototypes.item) do
        local item = (data.raw[item_type] or {})[name]
        if item then
            item.inventory_move_sound = move_sound
            item.pick_sound = pick_sound
            item.drop_sound = drop_sound
            return
        end
    end
    error("Could not find item " .. name)
end

add_sound_item("ash", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("chromium", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("gravel", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("coke", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("nichrome", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("iron-oxide", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("active-carbon", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("zinc-chloride", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("tailings-dust", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("soil", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("nexelit-ore", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("drill-head", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("sand", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("pure-sand", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("limestone", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("organics", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("coarse", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("rich-dust", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("coal-dust", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("chromite-sand", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("nexelit-plate", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("sand-casting", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("lithium-peroxide", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("nexelit-cartridge", item_sounds.mechanical_inventory_move, item_sounds.mechanical_inventory_pickup, item_sounds.mechanical_inventory_move)
add_sound_item("saturated-nexelit-cartridge", item_sounds.mechanical_inventory_move, item_sounds.mechanical_inventory_pickup, item_sounds.mechanical_inventory_move)
add_sound_item("lime", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("fuelrod-mk01", item_sounds.nuclear_inventory_move, item_sounds.nuclear_inventory_pickup, item_sounds.nuclear_inventory_move)
add_sound_item("fawogae", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("fawogae-substrate", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("flask", item_sounds.science_inventory_move, item_sounds.science_inventory_pickup, item_sounds.science_inventory_move)
add_sound_item("bonemeal", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("raw-borax", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("borax", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("ralesia", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("ralesia", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("rich-clay", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("ground-sample01", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("bio-sample01", item_sounds.science_inventory_move, item_sounds.science_inventory_pickup, item_sounds.science_inventory_move)
add_sound_item("alien-sample01", item_sounds.science_inventory_move, item_sounds.science_inventory_pickup, item_sounds.science_inventory_move)
add_sound_item("equipment-chassi", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("lab-instrument", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("lens", item_sounds.science_inventory_move, item_sounds.science_inventory_pickup, item_sounds.science_inventory_move)
add_sound_item("boron-trioxide", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("ralesia-seeds", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("niobium-ore", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("niobium-powder", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("niobium-dust", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("niobium-concentrate", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
--add_sound("mukmoux-fat", , )
add_sound_item("niobium-oxide", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("niobium-plate", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("glass-core", item_sounds.science_inventory_move, item_sounds.science_inventory_pickup, item_sounds.science_inventory_move)
add_sound_item("cladding", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("ppd", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("kevlar", item_sounds.wire_inventory_move, item_sounds.wire_inventory_pickup, item_sounds.wire_inventory_move)
add_sound_item("kevlar-coating", item_sounds.wire_inventory_move, item_sounds.wire_inventory_pickup, item_sounds.wire_inventory_move)
add_sound_item("nbfe-alloy", item_sounds.metal_small_inventory_move, item_sounds.metal_small_inventory_pickup, item_sounds.metal_small_inventory_move)
add_sound_item("nbfe-coating", item_sounds.wire_inventory_move, item_sounds.wire_inventory_pickup, item_sounds.wire_inventory_move)
add_sound_item("cladded-core", item_sounds.metal_large_inventory_move, item_sounds.metal_large_inventory_pickup, item_sounds.metal_large_inventory_move)
add_sound_item("copper-coating", item_sounds.wire_inventory_move, item_sounds.wire_inventory_pickup, item_sounds.wire_inventory_move)
add_sound_item("optical-fiber", item_sounds.wire_inventory_move, item_sounds.wire_inventory_pickup, item_sounds.wire_inventory_move)
add_sound_item("biofilm", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("filtration-media", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("coal-briquette", item_sounds.resource_inventory_move , item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("crushed-iron", item_sounds.resource_inventory_move , item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("crushed-copper", item_sounds.resource_inventory_move , item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("log", item_sounds.wood_inventory_move , item_sounds.wood_inventory_pickup, item_sounds.wood_inventory_move)
add_sound_item("treated-wood", item_sounds.wood_inventory_move, item_sounds.wood_inventory_pickup, item_sounds.wood_inventory_move)
add_sound_item("empty-fuel-canister", item_sounds.metal_chest_inventory_move, item_sounds.metal_chest_inventory_pickup, item_sounds.metal_chest_inventory_move)
add_sound_item("crushed-quartz", item_sounds.resource_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.resource_inventory_move)
add_sound_item("powdered-quartz", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)
add_sound_item("gunpowder", item_sounds.sulfur_inventory_move, item_sounds.resource_inventory_pickup, item_sounds.sulfur_inventory_move)